extends: 'airbnb'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
rules:
  max-len:
    - error
    - 120
  arrow-parens:
    - error
    - as-needed
  import/no-named-as-default:
    - off
  import/no-extraneous-dependencies:
    - off
  import/prefer-default-export:
    - off
  react/jsx-curly-spacing:
    - error
    - never
  react/jsx-equals-spacing:
    - error
    - never
  react/jsx-filename-extension:
    - off
  react/prop-types:
    - off
globals:
  customisation: true
env:
  browser: true
