version: 2
jobs:
  test:
    docker:
    - image: circleci/node
    steps:
    - checkout
    - run:
        name: Test
        command: yarn test
workflows:
  version: 2
  test:
    jobs:
    - test

